import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "@/GlobalRedux/provider";




export const metadata: Metadata = {
  title: "Your Next App",
  description: "Generated by create Scope",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        
      
      >
      <Providers>
      {children}
      </Providers>
       
      
      
    
      </body>
    </html>
  );
}
